/**
 * Professional README footer template
 */

export function generateFooter(updatedAt: string): string {
  const date = new Date(updatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `

---

<div align="center">

<sub>Last updated: ${date}</sub>

<br/>

<sub>Generated by <a href="https://github.com/opensource-showcase/opensource-showcase">opensource-showcase</a> • View raw data: <a href="contributions.json">contributions.json</a></sub>

</div>
`;
}
